CREATE DATABASE IF NOT EXISTS cms_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'cms_user'@'%' IDENTIFIED BY 'cms_pass2024';
GRANT ALL PRIVILEGES ON *.* TO 'cms_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
